[package]
name = "eye-of-reth"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.11"
jsonrpsee = "0.20.3"
serde = "1.0.193"
tokio = { version = "1.21", default-features = false }

thiserror = "1.0.50"
eyre = "0.6.10"
anyhow = "1.0.75"
serde_json = "1.0.111"

reth = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", branch = "main" }